### ISSUE TITLE
To connect to a local IRI node, do the following:Where do I run this code?

### ISSUE THREAD

**Issue by wangyuyuer** [iotaledger/iota.js#362]
![18ID3CJCH$G@H%QZ$JL39C9](https://user-images.githubusercontent.com/48520185/54595855-71f12d80-4a6e-11e9-9896-32d030c8cf8f.png)

**Comment by chrisdukakis** [comment]
Hi @wangyuyuer you can place this code in a .js file and run it with node.js

**Comment by pwalimbe** [comment]
When I did the same - I get 

$ node fb_index.js 
/Users/Prasanna/NodeProjects/iota-example/iota.js/fb_index.js:1
import { composeAPI } from '@iota/core'
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:749:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:868:12)
    at internal/main/run_main_module.js:21:11

So I did try by running the same code as .mjs and using experimental option. but still get this error:
node  --experimental-modules  fb_index.mjs
(node:20121) ExperimentalWarning: The ESM module loader is experimental.
file:///Users/Prasanna/NodeProjects/iota-example/iota.js/fb_index.mjs:1
import { composeAPI } from '@iota/core'
         ^^^^^^^^^^
SyntaxError: The requested module '@iota/core' does not provide an export named 'composeAPI'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:88:21)
