### ISSUE TITLE
Error with @iota/account: Cannot find module 'core-js'

### ISSUE THREAD

**Issue by sobolev-alexey** [iotaledger/iota.js#396]
Sample code to test
```
const { createAccount }  = require('@iota/account');
```
found in version `1.0.0-beta.15`

Console output:
```
node test.js
module.js:550
    throw err;
    ^

Error: Cannot find module 'core-js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/.../node_modules/@iota/converter/out/src/trits.js:3:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/.../node_modules/@iota/converter/out/src/index.js:8:10)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
```

**Comment by sobolev-alexey** [comment]
How to fix: 
```
npm i code-js
```

**Comment by obany** [comment]
This PR https://github.com/iotaledger/iota.js/commit/7978ba8db953af659e955162f3a0c20f073edbf3 adds core-js usage but fails to add the dependencies for individual packages.

The real fix is to add core-js as dependency of the packages that use it, we can't expect everyone to add it manually.
