### ISSUE TITLE
getbundle fails when reattachment use previous (same hash) bundle as tip

### ISSUE THREAD

**Issue by oskyk** [iotaledger/iota.js#401]
### Bug description

Basically what we have here is two bundles with the same bundle hash (i.e., bundle was reattached). This wouldn't be so unusual, except that one of the bundles used the other bundle as the tip when attaching.

In other words, the unconfirmed reattachment references the original confirmed bundle as its parent.

get_bundles() recursively follows the trunk of each transaction until it hits a different bundle hash (it was done this way to match the behaviour of the JS library), so when the client searches for the bundle for transaction PRHQ..., it finds all 8 transactions.

### Steps To Reproduce
```
Welcome to Node.js v12.5.0.
Type ".help" for more information.
> const composeAPI = require('@iota/core').composeAPI
undefined
> const iota = composeAPI({provider: 'https://nodes.thetangle.org:443'})
undefined
> iota.getBundle('PRHQBLFDCH9TDABLUCWOUBIDMOFGJVBEYUPX99PRQPVCWZLVQQAOUSIQZIKHDBQ9SQXNIGFRYZWMZ9999').then(console.log, console.error)
Promise [Object] {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined
}
> Error: Invalid bundle: [
 {
  "hash": "PRHQBLFDCH9TDABLUCWOUBIDMOFGJVBEYUPX99PRQPVCWZLVQQAOUSIQZIKHDBQ9SQXNIGFRYZWMZ9999",
  "signatureMessageFragment": "999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999",
  "address": "PVOOAZTFITWAHLHKJL9KGPGWPNOLOAHMLCBUYKWDX9AGKMXPXUCJJTBF9O9UQSPXYTUECRVZHKEKWTLEY",
  "value": 8000000000,
  "obsoleteTag": "YRINITY99999999999999999999",
  "timestamp": 1561572816,
  "currentIndex": 0,
  "lastIndex": 3,
  "bundle": "PKUPQCDLJKEORU9SIYIFCYTYGCZSBZYGHFPHSOG9NHKTVIIDEJTIKWBQLADJUBDJNPCZBNHSHWURHWLID",
  "trunkTransaction": "FTLYHKUZIPKOXTXO9NNEBAQXKCHQNTSBHVHYLNMVSKBLLENTLZSUAJIRVUTW9REAGQPMPTNXTYHOZ9999",
  "branchTransaction": "GREJ9EZLHKOVUUYWCCVL9OYAFKVLRQQMOTTZLDQEN9GVD99GFHQLHYWUXFMKAIVSYFU9KLSQSLER99999",
  "tag": "TRINITY99999999999999999999",
  "attachmentTimestamp": 1561660233178,
  "attachmentTimestampLowerBound": 0,
  "attachmentTimestampUpperBound": 3812798742493,
  "nonce": "JRFSVB999999999999999999999"
 },
 {
  "hash": "FTLYHKUZIPKOXTXO9NNEBAQXKCHQNTSBHVHYLNMVSKBLLENTLZSUAJIRVUTW9REAGQPMPTNXTYHOZ9999",
  "signatureMessageFragment": "IOFGXN9EDXAVZUIYLHBGRUCOWXXDQBUMHKIRE9AUEXSFIDQ9YUQFDOXVPOUD9PD9XYDXCVMLAQCYMVSSZZ9XBUOANCZLNSVDSCXGTFVWGPS9YHD9KAQZIBCEF9IXWYCSUQQFMBQBBDSKQWPYGLVPDVLLCDNPPWFNO9HSB9PTSRTGXNRSVSSFGIOYPRXLNKIKRBZTFRBNIJISDCMEMNXLHCGRWTAOYYFJTDSYVOQPUAZLIFABCKCHLMFFPKVPJYWTYSOKPWQBTWJMUHXBGWZQ9NWUSPZWXNCZGMURWCPJ9HYQEATSHKDPCCVLJWZOUT9GELVXMHOVW9QBDJPB9MJQYYUUZLYJRMBMRXPMLOMDUI9OCGOZSDMPUEHEGRIYLVTVHHGCQMDZJYTMEVHFFSILCPCNGVVHUVY9CHXRSGYRUWHPXNENMABK9CZNZNBAIMCSNTTJNNHXOHUZCY9KWXYDUXHKXNZDFEGKIYARXZVFSJWRGLZECJGQYOLRQPDTJUHFKKNFBVLVKGFSWPNYYVIOZMUBYUHEESPWDELTCTZCZBRTVADAKIZFSCDFPAWJONZUIEYQHGYVCIIWBRTERSMALZYDKKMKBKSBKUMHJIFQRPIWJVNZERTXMJVKSOWTAIOPAOVGGOGCWH9ODFGN9UYPPUL9LSBKJSTJ9FG9PBNDGHEA9DVKKPBQMJZIBRSSANOSDYXUXQF9BNJ9XMLRPIAUJFDEWVUCAKGSVEHIDMKEQZYRZL9AFALL9DVUWPRNSPKAIEVHRIXYTTUKSPHNOCUPRAUCZWABP9WZNWBQQMIAICLQALLXB9OWLVBUY9PPLKOAQSEEZQBUEMNAMRUSGLQRCJCPSCPJRFDP9TVWJK9QHUPNFJCIUPMZHIHYNUDSCHNOIW9F9OUTKXCZCHQMOXXKAQSHSZXKHSXWEV9WETXTNWINEVSDKFWLVAOLXZZFARAALPEMTEHKVJMCUTKAELWSTJFMYVIFKHQQAUERDOKVSPVGJIS9QILEVSKLN9ZAPTIZNKVWCPLCUMWOBMDLQYQWWXJHARTRWHRSQD9NYGBCWRJSDMPVCUFPBEP9MIGQFBJQDTTJDUTBOQCDAZQRSTGRWOJHHYLLNJQQHZLFCXPJFMPD9BWWYWSRUEZEARPOTUZECMUNWQTPFPRGXUKBBG9ZFDZXHXQVXEJTQ9PLICWQQAENSJQGMCWCWXPOTTJPIODKCLDBYWRWUTZOIZRAOLGRAEW9RVHE9FHASKSCXSQLBRDCWNQLYEVLTFOJ9NUSEJHKINOT9WJHVBFRUYJDAFMQCVMCDAON9CZFGKPDN9SVBEIUQMWPMGTIMVRVZPOJKYFHK9ITLBAVZMKRNAGIHHNN9CZLLRLZRGOQXGDSATVTEOOAXDCBLFPSWXEZMSTTRKQLODREFVKKUKCRPGLWJIWQRGV9GCSDFTYZXZKFDQDDPFSBDOYTTYRPONKEKXHJHPSUWDFQFVKGOMDWGTWXRAUWNBDCIRYHIKEATQEUDDITFLPDBNHEVIGWCOPXJNQZAZYDLEYHNZHFYMGB9SATKRXTZYSXGRYUOUCDVLHSNXVWQFFCIOYSIYFOYIZG9EMNXZBQLMSORDJHJIBJILETVEVXXJQFKVTCXAIFOAMDPIEXHNHZG9GBAY9GXH9TYHRCOFGWQSTWYOZ9COHKMVDETNBCFXWSOLEBDKHUJHRJ9MVCATCG9AAAPSYONRAGH9UZEIJAPCXWZDEUNKWXRLYUHFN9TKQBRVIBFUGRJDCZWGUCZCMXCYNJWXOYIDL9PDVRROLLSNLNBMVNHSUAJJWE9APLPGDIJTHDLUFXFYODOFWVWMXGWZVDHLEQEEHWPYAZKTINPNJ9MFCQEEDMTZROHILMJM9KF9BMOOMRAVNREQI9GEVPPDG9IJIFZJPOKHYJRJVCUOAODRBTFPMMACMPWZGHKOSDLCEQTXVKLPCATIGYNUUQCJHNINFRQLFSFJACDJZZHOQKO9Q9RFIQLQIVQJXOMEZISMXTABGI9BWLCKMEBTALEGAFQDOGJVBXAJDFJMEGCVEDSRYZIQSVPZTEUNGADSGMMZK9HKQI9Z9VMJTAEUXDSINVZJYTEPUZPYUPIRJYDMRJLBGKJWFKECIJQHE9XSURFLDUYMGR9NGGHEQWFIXZLGXRGZNJRLUTUSHQPRKAYCNCAOOWRUC",
  "address": "LAYNNMMTDXZTVBQJSBRLRUMWAJALP9HFXWOREAVXBVGOFTUJGU9ZAJEGVPMMCEDQHYBQMYY9NTPNKCFRY",
  "value": -8001000000,
  "obsoleteTag": "999999999999999999999999999",
  "timestamp": 1561572816,
  "currentIndex": 1,
  "lastIndex": 3,
  "bundle": "PKUPQCDLJKEORU9SIYIFCYTYGCZSBZYGHFPHSOG9NHKTVIIDEJTIKWBQLADJUBDJNPCZBNHSHWURHWLID",
  "trunkTransaction": "JQANNDTAHEXWFQSQYNXX9OLFTDRQQPJUW9GNEFGWRZUVRNOZQCAOLPCNXR9IUCTVVTYLRRGFXBHHA9999",
  "branchTransaction": "GREJ9EZLHKOVUUYWCCVL9OYAFKVLRQQMOTTZLDQEN9GVD99GFHQLHYWUXFMKAIVSYFU9KLSQSLER99999",
  "tag": "999999999999999999999999999",
  "attachmentTimestamp": 1561660231923,
  "attachmentTimestampLowerBound": 0,
  "attachmentTimestampUpperBound": 3812798742493,
  "nonce": "LSY9H9999999999999999999999"
 },
 {
  "hash": "JQANNDTAHEXWFQSQYNXX9OLFTDRQQPJUW9GNEFGWRZUVRNOZQCAOLPCNXR9IUCTVVTYLRRGFXBHHA9999",
  "signatureMessageFragment": "UTXOOKMEOIMFQEIW9MIURALVCEINRXMDKCLS9UTDUROYUPB9DLSF9DARBDFPEEJRDWZFKQMMZTBGTGDD9EZVEKGDKBBSMDYVTRMNHGUPUDBPYIPIWCHOCASITKMMBUFQDTQQXUFHBCKHUMSEHDNCZHNIDECFVKEJSWDOUQ9YGG9XIGMKCMPIHITSMYSWQZHKYZNWJSTD9ZQHCRVXCKEVSFRXTSYZGESOJDTWCELOUXMKWEMDUM9BRWNSKPKBRIGSDGPDTKRDYZXRWU9EAMFNEHRYHHNXVXL9KDAPZPZSWWBJIHLXKJEHPPBLWVWULCNJYETWLADDKP9IMVQRPEKHJZODPGMXT9EVS9UNA9P9IRIVSII9XQ9PYEQRLXFGUHJDOYHZCWMQAIXRRVDOFFGYYF9XAODULIYSIYPUVDRGAIZMEBERGWJAUDVNXETVILLQLPDVGYDRFRLMQSNBRHULWIEVTFPCQGGDTFCBIBT9CREHYOR9UTTCWPXILXLDZZYGQGFEQCZLEHZDYYROWWEWBTKSOHKYZHQXSMOYUZHNCZHUUQOJTWZKOYDFNQLTYWCFEF9C9TPPBKZYLBXDGCPDRYOPWEASCIDQGJZUXMN9KTEMDAGUSQNVUITEYHAPYFIEBLOICXH9WXBAKZMXCWRWUEPCNQMOJCYYLQQFWGZEBJMDAXZPAJGOJFCIFYBYQHCZJPEFGUIBHTCUULCVELGWGLURYBEIXWQV9OJBNCIDSIQCDQRIYBBLVFNEBYRMRUXKWGKHISWMGZRQ9MGPF9KSEYBYHUVHLSVVBTYSRSETEDNKCTLXDG9WDQWFABLEPFSCCLOWEDEIXAKDCFZQQTRQKVDQBNYPMZQJYYVVMFJQNWAE9XBTJDMMYCUWS9CZBENHGOCZDQUODVUPIG9XPMSADNAGYHXPB9BODYVPJSREJGKDVRSBXWYUHXUOFUYNRWSCWSFYBWLWNSGWAZLTP9KEEBNIHFGIQLAJOI9SKXTIAMGBKRJDQD9SHWILTPNYTKVJ9WEMEGNWFDGEBNNQR9NQ9AETKUKHBRTQUFTR9WVGGTCRYCODGG9UVPR9BKCACPHPWCEEMCNKJYPRPFGSMDIEEQUOWHSRXGECKCXYWRWQILSGEYYAVRUQPGZTCNBAPTBWJRVTZKQYKGEIPBJQOWMZRVLXQNCRPRCWMCRQIXYTOPBGTZUTDFQSQMBJBURHHXAZPDTI99ASGCYASIBDPEPJSMR9ZEBXHOLI9IZOVGBXMMFPUOVZMWQYFIAFPMHJKWKNWNVZPSGPILDRFXXBGZWBTISI9CXWMEAFVEOCZ9CHQBXIFVHEAZSSLCS9CWFNLAQWMXNNPPQUPRIXIADSIYPQGFTMIEUCPBOVWMYIEP9LZZNUJH9WNYLHYEDDUZDSLEGFENVDOWTFSKNUWVIYMQAHZNENVEHSUAJGTRDADPOIJUIXAYODEA9QONLCJFGP9LXKAFZKQYTCT99VML9YLYNERCFJD9VIZVSFYNPGLQBAQQN9IXVLYMUGJGWJTKLGD9WVVBDYBYGRB9PNUYQGOKWEFOKBSRUDQVQYYCHYUYRLNLBBXQQYUWFFHXKKPK9RIQASFIPZJZHXYONMTYWD9SQC9ZJGQOHXFHUPOCVEIDHFRSIBHNXRXKKRGZKESCXMUYEOVGQWOA9WLGJVRQMB9CPBUKTCSPBXYLDEYMGTZOPDTWYLGJXABKITZOFPGGUSORXLXR9YGNAXYFALBNOYZ9QIWWYSGYWPHQDIUUXKTMLKLKXFYSXOKXQUCDOAGCODT9M9AJLNISZZORPIYGRJZNPQMQPPJJUGMJOQRCIKOQNAEBOQLIHBHMKHYMP9DGMYDAFQCFF9YRDENQHEXQ9LNCIPSRYMWI9DZDWJQIWTXZBWGMNNQOUKWQEMORBPXI9JILXNCEC9MCCPSEBGLTN9KDDHGIT9NV9NMGQGHPZJ9LEGSMGSLBJHDRQPAGFAQDVBMAAGVELQOENWPISGYQHQXRSCELEAXBGCLFYVN9LJJLRBCPQZM9ZSZBK99GAB9WBGSJZTMIHCJUAUZFCCIGVLUSURBVYDJXPTGIJNGVGUT9RENXRWYDIZAWVLQZODLWMJKGEWT9UNGAXNSBDQP9QDRILQVXQOCB9ZMUDOKFWLRQDKSBRAI9BHSWWUXM9ZRKMEMMTZBTCYPZTPHZB",
  "address": "LAYNNMMTDXZTVBQJSBRLRUMWAJALP9HFXWOREAVXBVGOFTUJGU9ZAJEGVPMMCEDQHYBQMYY9NTPNKCFRY",
  "value": 0,
  "obsoleteTag": "999999999999999999999999999",
  "timestamp": 1561572816,
  "currentIndex": 2,
  "lastIndex": 3,
  "bundle": "PKUPQCDLJKEORU9SIYIFCYTYGCZSBZYGHFPHSOG9NHKTVIIDEJTIKWBQLADJUBDJNPCZBNHSHWURHWLID",
  "trunkTransaction": "GTTHWYNNQEHSFOTRQXVKAAFRUOUDEHYFMOTUCGHNUDXRJNITRWOPXB9OPDD9TLV9PQZVGBPZAAVWA9999",
  "branchTransaction": "GREJ9EZLHKOVUUYWCCVL9OYAFKVLRQQMOTTZLDQEN9GVD99GFHQLHYWUXFMKAIVSYFU9KLSQSLER99999",
  "tag": "999999999999999999999999999",
  "attachmentTimestamp": 1561660227314,
  "attachmentTimestampLowerBound": 0,
  "attachmentTimestampUpperBound": 3812798742493,
  "nonce": "VOOGTA999999999999999999999"
 },
 {
  "hash": "GTTHWYNNQEHSFOTRQXVKAAFRUOUDEHYFMOTUCGHNUDXRJNITRWOPXB9OPDD9TLV9PQZVGBPZAAVWA9999",
  "signatureMessageFragment": "999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999",
  "address": "999999999999999999999999999999999999999999999999999999999999999999999999999999999",
  "value": 0,
  "obsoleteTag": "999999999999999999999999999",
  "timestamp": 0,
  "currentIndex": 0,
  "lastIndex": 0,
  "bundle": "999999999999999999999999999999999999999999999999999999999999999999999999999999999",
  "trunkTransaction": "999999999999999999999999999999999999999999999999999999999999999999999999999999999",
  "branchTransaction": "999999999999999999999999999999999999999999999999999999999999999999999999999999999",
  "tag": "999999999999999999999999999",
  "attachmentTimestamp": 0,
  "attachmentTimestampLowerBound": 0,
  "attachmentTimestampUpperBound": 0,
  "nonce": "999999999999999999999999999"
 }
]
    at node_modules/@iota/core/out/guards.js:225:23
    at Array.forEach (<anonymous>)
    at Object.exports.validate (node_modules/@iota/core/out/guards.js:221:16)
    at node_modules/@iota/core/out/core/src/createGetBundle.js:50:54
    at PassThroughHandlerContext.finallyHandler (node_modules/bluebird/js/release/finally.js:57:23)
    at bound (domain.js:415:14)
    at PassThroughHandlerContext.runBound (domain.js:428:12)
    at PassThroughHandlerContext.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:17:14)
```

### Expected behaviour
It should parse bundle correctly

More info on: https://github.com/iotaledger/iota.lib.py/issues/225

**Comment by chrisdukakis** [comment]
Hi @oskyk , `getBundle` traverses through trunk transaction starting from tail, until it reaches head; 

https://github.com/iotaledger/iota.js/blob/fedadf72b0c3193156751220339617d174cd08c7/packages/core/src/createTraverseBundle.ts#L74

Bundle hash isn't used for the exact reason you mentioned. The issue with the above invalid bundle is that node returns an empty transaction (all 9s). I don't really know why is that, but `getBundles` rejects as planned.

Hey @todofixthis, please take a look at the [L74](https://github.com/iotaledger/iota.js/blob/fedadf72b0c3193156751220339617d174cd08c7/packages/core/src/createTraverseBundle.ts#L74). Perhaps [this line](https://github.com/iotaledger/iota.lib.py/blob/97cdd1e241498446b46157b79b2a1ea2ec6d387a/iota/commands/extended/get_bundles.py#L103) allows traversal of identical references in pyota.

**Comment by obany** [comment]
The all 9s means the transaction was removed by a snapshot.
