### ISSUE TITLE
Account dies after error from node received

### ISSUE THREAD

**Issue by NemesisFLX** [iotaledger/iota.js#404]
### Bug description
The account module throws cryptic error if it receives messages from a node with 4XX,5XX response.

### Steps To Reproduce
1. Build an application that needs a listner, like monitoring incoming deposits:
```
const provider = 'https://nodes.thetangle.org:443'

const account = accountModule.createAccount({
     seed,
     provider
})

generateCDA()

account.on('pendingDeposit', ({address, bundle}) => {
   console.log(address)
   console.log(bundle)
})

async function generateCDA(){
   cda = await account.generateCDA({
       timeoutAt : (new Date()).getTime() + 500000,
       expectedAmount : 10,
   })
   console.log(cdaModule.serializeCDAMagnet(cda))
   console.log(checksum.addChecksum(cda.address.substring(0, 81)))
}
```
2. Wait for the node to throw an error, artifically throw an error on your node or similar

### Expected behaviour
The account module should give a less cryptic error message which tells you the cause and propably should have a config to just retry 3 consecutive times

### Actual behavior
The application dies with cryptic message

### Errors
```
Unhandled rejection Error [ERR_UNHANDLED_ERROR]: Unhandled error. (Request error: com.iota.iri.service.ValidationException: Invalid bundles input)
   at Object.emit (events.js:178:17)
   at /home/felix/Development/iota_account_js/node_modules/@iota/account/out/account/src/account.js:184:59
   at tryCatcher (/home/felix/Development/iota_account_js/node_modules/bluebird/js/release/util.js:16:23)
   at Promise._settlePromiseFromHandler (/home/felix/Development/iota_account_js/node_modules/bluebird/js/release/promise.js:517:31)
   at Promise._settlePromise (/home/felix/Development/iota_account_js/node_modules/bluebird/js/release/promise.js:574:18)
   at Promise._settlePromise0 (/home/felix/Development/iota_account_js/node_modules/bluebird/js/release/promise.js:619:10)
   at Promise._settlePromises (/home/felix/Development/iota_account_js/node_modules/bluebird/js/release/promise.js:695:18)
   at _drainQueueStep (/home/felix/Development/iota_account_js/node_modules/bluebird/js/release/async.js:138:12)
   at _drainQueue (/home/felix/Development/iota_account_js/node_modules/bluebird/js/release/async.js:131:9)
   at Async._drainQueues (/home/felix/Development/iota_account_js/node_modules/bluebird/js/release/async.js:147:5)
   at Immediate.Async.drainQueues [as _onImmediate] (/home/felix/Development/iota_account_js/node_modules/bluebird/js/release/async.js:17:14)
   at runCallback (timers.js:705:18)
   at tryOnImmediate (timers.js:676:5)
   at processImmediate (timers.js:658:5)
```

**Comment by chrisdukakis** [comment]
So this is actually the `error` event which should be handled. Node triggers uncaught rejection if no listener exists for an emitted `error` event. I added a noop handler which prevents the crash, even if no `error` listeners are set up. However it's always good to set up one, at least for debugging:
```JS
account.on('error', () => {
  /...
})
```
