### ISSUE TITLE
Error: Insufficient balance

### ISSUE THREAD

**Issue by yehia67** [iotaledger/iota.js#424]
Hello, 
I am new at IOTA, I follow the getting-started documentation (https://docs.iota.org/docs/getting-started/0.1/tutorials/send-iota-tokens) I want to send test token to another address but it keep giving me this error.
```
`GetNewAddressOptions`: 1 options are deprecated and will be removed in v.2.0.0. 

Sending 500i to WLSTCOWIVJDMVYRAEKKQJUFYNCJNRFUEGNSIVWGPATLIFMEDRUGNVJVIUMOHGOQYOJGGWGXUQAOXW9FIZ
Error: Insufficient balance
    at Object.exports.hasSufficientBalance (/home/yehia/Documents/Projects/IOTA/yarab/iota.js/node_modules/@iota/core/out/core/src/createGetInputs.js:118:15)
    at /home/yehia/Documents/Projects/IOTA/yarab/iota.js/node_modules/@iota/core/out/core/src/createGetInputs.js:83:57
    at PassThroughHandlerContext.finallyHandler (/home/yehia/Documents/Projects/IOTA/yarab/iota.js/node_modules/@iota/core/node_modules/bluebird/js/release/finally.js:57:23)
    at PassThroughHandlerContext.tryCatcher (/home/yehia/Documents/Projects/IOTA/yarab/iota.js/node_modules/@iota/core/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/yehia/Documents/Projects/IOTA/yarab/iota.js/node_modules/@iota/core/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/home/yehia/Documents/Projects/IOTA/yarab/iota.js/node_modules/@iota/core/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/home/yehia/Documents/Projects/IOTA/yarab/iota.js/node_modules/@iota/core/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/home/yehia/Documents/Projects/IOTA/yarab/iota.js/node_modules/@iota/core/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/home/yehia/Documents/Projects/IOTA/yarab/iota.js/node_modules/@iota/core/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/yehia/Documents/Projects/IOTA/yarab/iota.js/node_modules/@iota/core/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/yehia/Documents/Projects/IOTA/yarab/iota.js/node_modules/@iota/core/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/yehia/Documents/Projects/IOTA/yarab/iota.js/node_modules/@iota/core/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

```

I checked my balance and it is 2000i (https://devnet.thetangle.org/address/IOWPPONJTYHHVRFRGFRWRVQU9VDMQYLEVVEABJPW9PT9F9SYMGIOFDXPYSLGESFTMBSJECQEPLHGWWYRZCMDDUZNCA) 

my code 
```
const Iota = require('@iota/core');

// Create a new instance of the IOTA API object
// Use the `provider` field to specify which node to connect to
const iota = Iota.composeAPI({
    provider: 'https://nodes.devnet.iota.org:443'
});

// Replace this seed with the one that owns the address you used to receive free Devnet tokens 
const seed =
    'IOWPPONJTYHHVRFRGFRWRVQU9VDMQYLEVVEABJPW9PT9F9SYMGIOFDXPYSLGESFTMBSJECQEPLHGWWYRZCMDDUZNCA';

// Create a wrapping function so you can use async/await
const main = async() => {

    // Create a different address from your seed to send the tokens to
    // Be sure that you have never withdrawn from this address before 
    const receivingAddress = await iota.getNewAddress(seed, {
        index: 2,
        total: 1
    });

    // Construct a bundle that transfers the tokens to your new address
    const transfers = [{
        value: 500,
        address: receivingAddress[0],
        tag: 'MYMAGIC'
    }];

    console.log('Sending 500i to ' + receivingAddress);

    try {
        // Construct bundle and convert to trytes
        const trytes = await iota.prepareTransfers(seed, transfers);
        // Send bundle to node.
        const response = await iota.sendTrytes(trytes, 3, 9);

        console.log('Bundle sent');
        response.map(tx => console.log(tx));
    } catch (error) {
        console.log(error);
    }
}

main(); 
```
code you tell me please what I am doing worng?

**Comment by laumair** [comment]
@yehia67 [prepareTransfers](https://github.com/iotaledger/iota.js/tree/next/packages/core#module_core.prepareTransfers) checks for balance on your addresses before signing them. Are you sure your seed has (some) addresses that have balance?

**Comment by yehia67** [comment]
@laumair  when I requested the free test token was for the seed. I will try to generate an address from the seed and gave it test token is that right?

**Comment by yehia67** [comment]
I had replaced my seed with an address generated from this seed 
```
// Replace this seed with the one that owns the address you used to receive free Devnet tokens 
const seed =  '9VIT9JCB9COPCTMOIFUEJVGUNDLSSJQCORYMEAZHRAUJXH9HGNI99BMLQDQOZNCLNVOLFMSFUIVPMYXDWEZFSZQROC';
```
but it still gave me the same error

**Comment by chrisdukakis** [comment]
@yehia67 I think it needs to be the first address, otherwise `prepareTransfers` won't detect it. Make sure that the transaction that funds the address exists in the node you connect to. This is due to the way `prepareTransfers` is coded, it requires existence of transactions from address 0 up to the one with balance that can be used as input.

**Comment by yehia67** [comment]
Yes It works Thanks @chrisdukakis  and @laumair
