### ISSUE TITLE
tailTransactionHash returns "Invalid Bundle" error

### ISSUE THREAD

**Issue by NomanNasirMinhas** [iotaledger/iota.js#569]
## Bug description

JS core package method returns "Error: Invalid bundle" even when all following conditions are true
- Addresses in value transactions have a 0 trit at the end, which means they were generated using the Kerl hashing function
- Transactions in the bundle array are in the same order as their currentIndex field
- The total value of all transactions in the bundle sums to 0
- The bundle hash is valid

## Version

Which version of the library are you running?

- Version: 1.0.0-beta.23

## IOTA network

Which node are you connected to and which IOTA network is it in?

- Node URL:  https://nodes.iota.cafe:443
- Network: Mainnet

## Hardware specification

What hardware are you using?

- Operating system: Windows 10
- RAM: 8 GB
- Number of cores: 4
- Device type: Laptop

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

```
////////////////////////////////////////////////
// Run the following Code                       //
////////////////////////////////////////////////

const Iota = require('@iota/core');
const Extract = require('@iota/extract-json');

// Connect to a node
const iota = Iota.composeAPI({
  provider: YOUR_NODE_URL
});

// Define the tail transaction hash of the bundle whose messages you want to read
const tailTransactionHash = TRANSACTION_HASH

// Get the transaction objects in the bundle
iota.getBundle(tailTransactionHash)
  .then(bundle => {
    // Extract and parse the JSON messages from the transactions' `signatureMessageFragment` fields
    console.log(JSON.parse(Extract.extractJson(bundle)));
  })
  .catch(err => {
    console.error(err);
  });
```

## Expected behaviour

Return transaction's message in JSON form

## Actual behaviour

Getting "Invalid Bundle" error

## Errors

```
Error: Invalid bundle: [
 {
  "hash": "ZWPBDMAFGSSGGNJFWATTYHDP9PYEIWRULDMKBZPWISVFGEMBQQYHVNLXUL9JIJ9FKZKTF9UBDMEOZ9999",
  "signatureMessageFragment": "999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999",
  "address": "999999999999999999999999999999999999999999999999999999999999999999999999999999999",
  "value": 0,
  "obsoleteTag": "999999999999999999999999999",
  "timestamp": 0,
  "currentIndex": 0,
  "lastIndex": 0,
  "bundle": "999999999999999999999999999999999999999999999999999999999999999999999999999999999",
  "trunkTransaction": "999999999999999999999999999999999999999999999999999999999999999999999999999999999",
  "branchTransaction": "999999999999999999999999999999999999999999999999999999999999999999999999999999999",
  "tag": "999999999999999999999999999",
  "attachmentTimestamp": 0,
  "attachmentTimestampLowerBound": 0,
  "attachmentTimestampUpperBound": 0,
  "nonce": "999999999999999999999999999"
 }
]
    at /home/runner/Read-a-transaction-from-the-Tangle/node_modules/@iota/core/out/guards.js:225:23
    at Array.forEach (<anonymous>)
    at Object.exports.validate (/home/runner/Read-a-transaction-from-the-Tangle/node_modules/@iota/core/out/guards.js:221:16)
    at /home/runner/Read-a-transaction-from-the-Tangle/node_modules/@iota/core/out/core/src/createGetBundle.js:50:54
    at PassThroughHandlerContext.finallyHandler (/home/runner/Read-a-transaction-from-the-Tangle/node_modules/bluebird/js/release/finally.js:57:23)
    at PassThroughHandlerContext.tryCatcher (/home/runner/Read-a-transaction-from-the-Tangle/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/runner/Read-a-transaction-from-the-Tangle/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/runner/Read-a-transaction-from-the-Tangle/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/runner/Read-a-transaction-from-the-Tangle/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/runner/Read-a-transaction-from-the-Tangle/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/runner/Read-a-transaction-from-the-Tangle/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/runner/Read-a-transaction-from-the-Tangle/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/runner/Read-a-transaction-from-the-Tangle/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/runner/Read-a-transaction-from-the-Tangle/node_modules/bluebird/js/release/async.js:15:14)
```

**Comment by laumair** [comment]
@NomanNasirMinhas It looks like the node you are querying doesn't have the complete trytes for the provided transaction hash. 

If you analyse the transaction object, all fields have empty / null trytes. Considering that, it is indeed correct for the bundle validation to fail.

**Comment by NomanNasirMinhas** [comment]
@laumair so does that means that I should change node? because when I am fetching this transaction from https://explorer.iota.org/ it is returning me transaction correctly. So, should I setup a new node? or if there are nodes which I can use kindly mention it.

**Comment by laumair** [comment]
> when I am fetching this transaction from https://explorer.iota.org/ it is returning me transaction correctly

That's because https://explorer.iota.org/ queries a [permanode](https://blog.iota.org/introducing-chronicle-a-permanode-solution-8e506a2e0813). 

IOTA nodes do not retain all transaction history. They perform local snapshots to prune transactions after a certain point. 

I would suggest keeping a local copy of the transactions you send to the tangle.
