### ISSUE TITLE
documentation is misleading when it comes to sending transactions

### ISSUE THREAD

**Issue by capaj** [iotaledger/iota.js#65]
I have:
```javascript
iota.api.sendTransfer(seed, 2, 18, [
  {
    address: 'AIB9GPOOOJFPWOKNLHUU9NSUDHDYJHDQL9OLYXLQEAXYWEARPAMPWPDKTZYOOM9KTWYDMFNNILLEKB9N9HJOSUEJLD',
    value: 4
  }
], (err, data) => {
  console.log('err: ', err)
  console.log('data: ', data)
})
```

now when I run that I get:
```
capaj@capaj-i7-4771:~/git_projects/gratiota$ node test.js
err:  Error: Request Error: COMMAND attachToTangle is not available on this node
    at Object.requestError (/home/capaj/git_projects/gratiota/node_modules/iota.lib.js/lib/errors/requestErrors.js:11:12)
    at makeRequest.prepareResult (/home/capaj/git_projects/gratiota/node_modules/iota.lib.js/lib/utils/makeRequest.js:167:24)
    at exports.XMLHttpRequest.request.onreadystatechange (/home/capaj/git_projects/gratiota/node_modules/iota.lib.js/lib/utils/makeRequest.js:61:25)
    at exports.XMLHttpRequest.dispatchEvent (/home/capaj/git_projects/gratiota/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/home/capaj/git_projects/gratiota/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/home/capaj/git_projects/gratiota/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
data:  undefined
```

is this command removed from IRI? Is the JS lib out of date?

**Comment by capaj** [comment]
The desktop wallet has spamming implemented with the same call:
https://github.com/iotaledger/wallet/blob/4a50e49c15c76ec57793614eafaa2edf54352927/ui/js/ui.spam.js#L67

so that might be why the network spammer was disabled in latest wallet, right?

**Comment by capaj** [comment]
Oh, nodes have this disabled with a CLI flag so the ones I tried have this probably disabled.

**Comment by kgrsajid** [comment]
I think, your original title was the right one. All the public nodes won't have support for attachToTangle method. You need to setup your own full node for it.

But yes, this is not mentioned in the documentation. I had to struggle a lot to overcome this issue. Luckily I've found this proxy solution - [https://github.com/TimSamshuijzen/iotaproxy/](url)
It will let you to do PoW without running full node. :)

And also I needed send options parameter to send IOTA more than 0. You won't find it in the documentation as well.

I think overall documentation needs to be updated.

I hope this resolves this issue for you. 👍

**Comment by capaj** [comment]
Actually iotaproxy is not very reliable yet-maybe on Windows it is, I only tried on Ubuntu. Will try on Windows next weekend.

**Comment by kgrsajid** [comment]
I am using iotaproxy on my Macbook. It's working fine (though I needed to change the CORS header).
I didn't see many request failed by using it. But for production use, I think you should run a full node. For testing purpose, this is a great tool.

**Comment by cyclux** [comment]
@capaj This issue with timeout on iotaproxy has been fixed.

**Comment by chrisdukakis** [comment]
I'll include all methods for doing PoW in docs, and explain that [default](https://github.com/iotaledger/iota.lib.js/blob/next/lib/api/extended/createSendTrytes.ts#L26) method requires `attachToTangle` command to be available in iri API.

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
