### ISSUE TITLE
sendAdvanced function inputs 

### ISSUE THREAD

**Issue by esmaykel** [iotaledger/iota.js#757]
Hello, I´m trying to test @iota with the transaction example and I have the next error message: 
 
`Error: You must specify some inputs
    at buildTransactionPayload (/home/chrysalis/Documents/node_modules/@iota/iota.js/dist/cjs/index-node.js:2291:19)
    at sendAdvanced (/home/chrysalis/Documents/node_modules/@iota/iota.js/dist/cjs/index-node.js:2270:36)
    at /home/chrysalis/Documents/transaction.js:128:64
    at Generator.next (<anonymous>)
    at fulfilled (/home/chrysalis/Documents/transaction.js:45:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

¿Could someone help me what is the reasons of that?
Thanks

**Comment by obany** [comment]
If  you are running the transactions example, make sure you have pointed the API_ENDPOINT to the devnet https://wiki.iota.org/chrysalis-docs/devnet

Also use the faucet to request some test funds to a seed/address that you can use.

This error is most likely because the mnemonic and addresses have no test funds on them
